
name: Context workflow

on:
  push:
    branches: ["main"]
    

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print github context
        env: 
          GITHUB_CONTEXT_ACTOR: $${{github.actor}}
        run: |
          echo "Hello $GITHUB_CONTEXT_ACTOR"

 